---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/Dev
  children:
    - name: DevDict
      type: udm.Dictionary
      entries:
        datasource.url: jdbc:mysql://localhost:3306/demo
        datasource.username: admin
        smoke.test.url: http://localhost:8080/petclinic
        smoke.test.expectedResponse: Chiens et chats
      encryptedEntries:
        # password should be set in external file : password: !value "key_for_password"
        datasource.password: password
    - name: Dev
      type: udm.Environment
      members:
      - ~Infrastructure/host-dev-vm/tomcat/tomcat_vh
      - ~Infrastructure/host-dev-vm/mysql
      - ~Infrastructure/host-dev-vm/smokeTestRunner
      dictionaries:
      - ~Environments/Dev/DevDict