---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/host-dev-vm
  type: overthere.SshHost
  os: UNIX
  address: 192.168.78.2
  username: demo
  password: !value "Infrastructure_host_dev_vm_password"
  children:
  - name: smokeTestRunner
    type: smoketest.Runner
  - name: tomcat
    type: tomcat.Server
    home: /opt/tomcat/tomcat-dev-9.0.21
    startCommand: sudo systemctl start tomcat
    stopCommand: sudo systemctl stop tomcat
    statusCommand: sudo systemctl status tomcat
    children:
    - name: tomcat_vh
      type: tomcat.VirtualHost
  - name: mysql
    type: sql.MySqlClient
    username: admin
    password: !value "Infrastructure_host_dev_vm_mysql_password"
    mySqlHome: /usr
    databaseName: demo
